apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-app
  namespace: production
type: Opaque
stringData:
  username: n8n
  password: robotdreams
  postgres-password: robotdreams
  postgresql-password: robotdreams
