apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: staging
spec:
  instances: 1

  storage:
    size: 1Gi
    storageClass: local-path

  superuserSecret:
    name: n8n-db-superuser

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-app
